name: 'UI QA Agent'
description: 'Compare PR screenshots against Figma designs linked in Jira tickets'
author: 'UI QA Agent'

branding:
  icon: 'eye'
  color: 'purple'

inputs:
  mode:
    description: 'Operation mode: detect, request, or analyze'
    required: true
  github-token:
    description: 'GitHub token for API access'
    required: true
  jira-base-url:
    description: 'Jira instance base URL (e.g., https://company.atlassian.net)'
    required: false
  jira-email:
    description: 'Jira account email'
    required: false
  jira-api-token:
    description: 'Jira API token'
    required: false
  figma-access-token:
    description: 'Figma personal access token'
    required: false
  figma-mock-mode:
    description: 'Enable mock mode for Figma to skip API calls (for testing)'
    required: false
    default: 'false'
  
  # AI Provider Selection
  ai-provider:
    description: 'AI provider to use: bedrock or azure'
    required: false
    default: 'azure'
  
  # AWS Bedrock Configuration
  bedrock-api-key:
    description: 'Bedrock API Key for authentication (recommended)'
    required: false
  bedrock-region:
    description: 'AWS region for Bedrock (default: us-east-1)'
    required: false
    default: 'us-east-1'
  bedrock-model-id:
    description: 'Bedrock model ID (default: us.anthropic.claude-sonnet-4-20250514-v1:0)'
    required: false
    default: 'us.anthropic.claude-sonnet-4-20250514-v1:0'
  aws-access-key-id:
    description: 'AWS access key ID for Bedrock (legacy auth)'
    required: false
  aws-secret-access-key:
    description: 'AWS secret access key for Bedrock (legacy auth)'
    required: false
  
  # Azure OpenAI Configuration
  azure-openai-api-key:
    description: 'Azure OpenAI API key'
    required: false
  azure-openai-endpoint:
    description: 'Azure OpenAI endpoint URL (e.g., https://your-resource.openai.azure.com/)'
    required: false
  azure-openai-deployment:
    description: 'Azure OpenAI deployment name'
    required: false
  azure-openai-api-version:
    description: 'Azure OpenAI API version (default: 2024-12-01-preview)'
    required: false
    default: '2024-12-01-preview'
  
  # Other inputs
  pr-number:
    description: 'Pull request number (for analyze mode)'
    required: false
  comment-id:
    description: 'Comment ID containing screenshots (for analyze mode)'
    required: false
  figma-links:
    description: 'JSON array of Figma links (for request mode)'
    required: false

outputs:
  has_figma_links:
    description: 'Whether Figma links were found (true/false)'
  figma_links:
    description: 'JSON array of found Figma links'
  jira_ticket:
    description: 'Jira ticket key that was processed'
  comment_id:
    description: 'ID of the posted comment'
  result:
    description: 'JSON result of the comparison analysis'
  status:
    description: 'Overall status (success/failure)'

runs:
  using: 'node20'
  main: 'dist/bundle/index.js'
