name: 'UI QA Agent'
description: 'Compare PR screenshots against Figma designs linked in Jira tickets'
author: 'UI QA Agent'

branding:
  icon: 'eye'
  color: 'purple'

inputs:
  mode:
    description: 'Operation mode: detect, request, or analyze'
    required: true
  github-token:
    description: 'GitHub token for API access'
    required: true
  jira-base-url:
    description: 'Jira instance base URL (e.g., https://company.atlassian.net)'
    required: false
  jira-email:
    description: 'Jira account email'
    required: false
  jira-api-token:
    description: 'Jira API token'
    required: false
  figma-access-token:
    description: 'Figma personal access token'
    required: false
  bedrock-region:
    description: 'AWS region for Bedrock (default: us-east-1)'
    required: false
    default: 'us-east-1'
  bedrock-model-id:
    description: 'Bedrock model ID (default: anthropic.claude-3-5-sonnet-20241022-v2:0)'
    required: false
    default: 'anthropic.claude-3-5-sonnet-20241022-v2:0'
  aws-access-key-id:
    description: 'AWS access key ID for Bedrock authentication'
    required: false
  aws-secret-access-key:
    description: 'AWS secret access key for Bedrock authentication'
    required: false
  pr-number:
    description: 'Pull request number (for analyze mode)'
    required: false
  comment-id:
    description: 'Comment ID containing screenshots (for analyze mode)'
    required: false
  figma-links:
    description: 'JSON array of Figma links (for request mode)'
    required: false

outputs:
  has_figma_links:
    description: 'Whether Figma links were found (true/false)'
  figma_links:
    description: 'JSON array of found Figma links'
  jira_ticket:
    description: 'Jira ticket key that was processed'
  comment_id:
    description: 'ID of the posted comment'
  result:
    description: 'JSON result of the comparison analysis'
  status:
    description: 'Overall status (success/failure)'

runs:
  using: 'node20'
  main: 'dist/bundle/index.js'

